CREATE TABLE moves (
    move_id integer,
    move_name_en text,
    move_name_jp text,
    type text,
    power integer,
    pp integer,
    priority integer,
    accuracy integer,
    damage_class text,
    effect_chance integer,
    effect_entries text,
    ailment text,
    move_category text,
    crit_rate integer,
    drain integer,
    flinch_chance integer,
    max_hits integer,
    min_hits integer,
    max_turns integer,
    min_turns integer,
    stat_chance integer,
    target text,
    PRIMARY KEY (move_id)
);